image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-domain.com
      paths:
        - path: /oren
          pathType: Prefix

replicaCount: 2
